export const NAVLINKS = [
    {
        id:0,
        name:'Home',
        href:'#home'
    },
    {
        id:1,
        name:'Features',
        href:'#features'
    },
    {
        id:2,
        name:'Works',
        href:'#works'
    },
    {
        id:3,
        name:'Pricing',
        href:'#pricing'
    }
]